[workspace]
members = [
    "vndf-client",
    "vndf-launcher",
    "vndf-server",
    "vndf-shared",
    "vndf-tests",
]
default-members = [
    "vndf-client",
    "vndf-shared",
    "vndf-tests",
]

[profile.dev.package."*"]
opt-level = 3
