[package]
name    = "vndf-server"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
env_logger = "*"
log        = "*"

[dependencies.vndf-shared]
path = "../vndf-shared"
