[package]
name    = "vndf-client"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
env_logger = "*"
ggez       = "*"
hecs       = "*"
log        = "*"
toml       = "*"

[dependencies.winit]
version  = "*"
features = ["serde"]

[dependencies.vndf-shared]
path = "../vndf-shared"
