[package]
name    = "vndf-client"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
env_logger = "*"
ggez       = "*"
log        = "*"
serde      = "*"
structopt  = "*"
time       = "*"
toml       = "*"

[target.'cfg(not(windows))'.dependencies]
wgpu  = "*"
winit = "*"

[dependencies.toadster]
path = "../toadster"

[dependencies.vndf-server]
path = "../vndf-server"

[dependencies.vndf-shared]
path = "../vndf-shared"
