[package]
name    = "vndf-client"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
futures  = "*"
ggez     = "*"
log      = "*"
serde    = "*"
time     = "*"
toml     = "*"
wgpu     = "*"
winit    = "*"
zerocopy = "*"

[dependencies.toadster]
path = "../toadster"

[dependencies.vndf-macros]
path = "../vndf-macros"

[dependencies.vndf-shared]
path = "../vndf-shared"
