[package]
name    = "vndf-tests"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"

[dependencies.vndf-server]
path = "../vndf-server"

[dependencies.vndf-shared]
path = "../vndf-shared"
