[package]
name    = "vndf-macros"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
quote       = "*"
syn         = "*"
