[package]
name    = "toadster"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
serde = "*"

[dependencies.rinnsal]
path = "../rinnsal"

[dependencies.slotmap]
version  = "*"
features = ["serde"]
