[package]
name    = "vndf-shared"
version = "0.1.0"
authors = ["Hanno Braun <hb@hannobraun.de>"]
edition = "2018"


[dependencies]
hecs     = "*"
log      = "*"
postcard = "*"
serde    = "*"

[dependencies.cgmath]
version  = "*"
features = ["mint", "serde"]

[dependencies.pid]
version  = "*"
features = ["serde"]

[dependencies.slotmap]
version  = "*"
features = ["serde"]
