name: Build, Test

on:
  pull_request:
    branches: [ master ]


jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies required by ggez
      run: sudo apt-get install libasound2-dev libudev-dev
    - uses: actions/checkout@v2
    - name: Build code and run tests
      run: ./scripts/build-all-and-test.sh
