name: Build, Test, Release, Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies required by ggez
      run: sudo apt-get install libasound2-dev libudev-dev
    - uses: actions/checkout@v2
    - name: Build code and run tests
      run: ./scripts/build-all-and-test.sh
    - name: Generate version name for release
      run: echo "::set-env name=VERSION::v$(date --utc +%Y%m%d-%H%M%S)"
    - name: Create tag and release
      id: create-release
      uses: avakar/tag-and-release@v1
      with:
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run:  echo "${{ steps.create-release.outputs.upload_url }}" > target/upload-url
    - uses: actions/upload-artifact@v1
      with:
        name: upload-url
        path: target/upload-url

  deploy_linux_client:
    runs-on: ubuntu-latest
    needs: build_test_release
    steps:
    - name: Install dependencies required by ggez
      run: sudo apt-get install libasound2-dev libudev-dev
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: upload-url
    - run: echo "::set-env name=UPLOAD_URL::$(cat upload-url/upload-url)"
    - name: Build Linux client
      run: ./scripts/build-linux-client.sh
    - name: Add Linux client to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: target/release-binaries/vndf-launcher-x86_64-unknown-linux-gnu.bin
        asset_name: Linux Client (x86_64)
